// <auto-generated />
using System;
using ArchGen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchGen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816181943_Initial_DB")]
    partial class Initial_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ArchGen.Domain.ArchGenEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDoProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DataUser");
                });
#pragma warning restore 612, 618
        }
    }
}
