// <auto-generated />
using System;
using ArchGen.InfraStructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchGen.InfraStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ArchGen.Domain.TemplateStructure", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSolucao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDoProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("ArchGen.Domain.TemplateStructure", b =>
                {
                    b.OwnsOne("ArchGen.Domain.Paths_CamadasEntity", "paths", b1 =>
                        {
                            b1.Property<Guid>("TemplateStructureID")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PathApplication")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PathConsole_OR_API")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PathDomain")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PathInfraStructure")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PathTests")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TemplateStructureID");

                            b1.ToTable("Template");

                            b1.WithOwner()
                                .HasForeignKey("TemplateStructureID");

                            b1.OwnsOne("ArchGen.Domain.ApplicationPathsArquivosEntity", "Application", b2 =>
                                {
                                    b2.Property<Guid>("Paths_CamadasEntityTemplateStructureID")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathDTOs")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathInterfaces")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathUseCases")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Paths_CamadasEntityTemplateStructureID");

                                    b2.ToTable("Template");

                                    b2.WithOwner()
                                        .HasForeignKey("Paths_CamadasEntityTemplateStructureID");
                                });

                            b1.OwnsOne("ArchGen.Domain.Console_OR_APIPathsArquivosEntity", "Console_OR_API", b2 =>
                                {
                                    b2.Property<Guid>("Paths_CamadasEntityTemplateStructureID")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ControllerArquivo")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Paths_CamadasEntityTemplateStructureID");

                                    b2.ToTable("Template");

                                    b2.WithOwner()
                                        .HasForeignKey("Paths_CamadasEntityTemplateStructureID");
                                });

                            b1.OwnsOne("ArchGen.Domain.DomainPathsArquivosEntity", "Domain", b2 =>
                                {
                                    b2.Property<Guid>("Paths_CamadasEntityTemplateStructureID")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathEntities")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathEnums")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathExceptions")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathInterfaces")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Paths_CamadasEntityTemplateStructureID");

                                    b2.ToTable("Template");

                                    b2.WithOwner()
                                        .HasForeignKey("Paths_CamadasEntityTemplateStructureID");
                                });

                            b1.OwnsOne("ArchGen.Domain.InfraStructurePathsArquivosEntity", "InfraStructure", b2 =>
                                {
                                    b2.Property<Guid>("Paths_CamadasEntityTemplateStructureID")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathData")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathMigrations")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathRepository")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PathServices")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Paths_CamadasEntityTemplateStructureID");

                                    b2.ToTable("Template");

                                    b2.WithOwner()
                                        .HasForeignKey("Paths_CamadasEntityTemplateStructureID");
                                });

                            b1.OwnsOne("ArchGen.Domain.TestsPathsArquivosEntity", "Tests", b2 =>
                                {
                                    b2.Property<Guid>("Paths_CamadasEntityTemplateStructureID")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ApplicationPathTests")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DomainPathTests")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Paths_CamadasEntityTemplateStructureID");

                                    b2.ToTable("Template");

                                    b2.WithOwner()
                                        .HasForeignKey("Paths_CamadasEntityTemplateStructureID");
                                });

                            b1.Navigation("Application")
                                .IsRequired();

                            b1.Navigation("Console_OR_API")
                                .IsRequired();

                            b1.Navigation("Domain")
                                .IsRequired();

                            b1.Navigation("InfraStructure")
                                .IsRequired();

                            b1.Navigation("Tests")
                                .IsRequired();
                        });

                    b.Navigation("paths")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
