// <auto-generated />
using System;
using ArchGen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchGen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ArchGen.Domain.ArchGenEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathApplication")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathInfrastructure")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathTests")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDoProjeto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DataUser");
                });
#pragma warning restore 612, 618
        }
    }
}
